#!/usr/bin/env python3
"""
Mwarokin Estates - Agentic Camera Monitoring System
Modern Python agentic monitoring for household security cameras
"""

import asyncio
import json
import logging
import time
import random
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import List, Dict, Optional, Any, Callable, Set
from collections import defaultdict
import threading
from pathlib import Path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("mwarokin-camera-system")


class CameraStatus(Enum):
    """Camera operational status"""
    ONLINE = "online"
    OFFLINE = "offline"
    STREAMING = "streaming"
    RECORDING = "recording"
    ERROR = "error"


class MotionStatus(Enum):
    """Motion detection status"""
    NO_MOTION = "no_motion"
    MOTION_DETECTED = "motion_detected"
    CONTINUOUS_MOTION = "continuous_motion"


class AlertSeverity(Enum):
    """Alert severity levels"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


class ZoneType(Enum):
    """Type of camera zone"""
    INTERIOR = "interior"
    EXTERIOR = "exterior"
    ENTRY = "entry"
    GARDEN = "garden"
    GARAGE = "garage"
    NURSERY = "nursery"
    KITCHEN = "kitchen"


@dataclass
class Camera:
    """Camera entity with state and metadata"""
    id: int
    name: str
    property_name: str
    zone_type: ZoneType
    status: CameraStatus = CameraStatus.ONLINE
    motion_status: MotionStatus = MotionStatus.NO_MOTION
    staff_attending: Optional[str] = None
    hue: int = 150
    brightness: float = 0.5
    last_motion_detected: Optional[datetime] = None
    stream_url: Optional[str] = None
    recording: bool = False
    snapshot_taken_at: Optional[datetime] = None
    firmware_version: str = "2.1.0"
    ip_address: str = "192.168.1.100"
    uptime_seconds: int = 0
    
    def to_dict(self) -> Dict:
        """Convert camera to dictionary"""
        return {
            "id": self.id,
            "name": self.name,
            "property_name": self.property_name,
            "zone_type": self.zone_type.value,
            "status": self.status.value,
            "motion_status": self.motion_status.value,
            "staff_attending": self.staff_attending,
            "last_motion_detected": self.last_motion_detected.isoformat() if self.last_motion_detected else None,
            "recording": self.recording,
            "uptime_seconds": self.uptime_seconds,
            "firmware_version": self.firmware_version
        }


@dataclass
class MotionEvent:
    """Motion detection event"""
    camera_id: int
    camera_name: str
    property_name: str
    timestamp: datetime
    duration_seconds: float
    motion_level: int  # 1-10
    region: str = "unknown"
    detected_by: str = "ai-detector"
    recorded_clip: Optional[str] = None
    
    def to_dict(self) -> Dict:
        return {
            "camera_id": self.camera_id,
            "camera_name": self.camera_name,
            "property_name": self.property_name,
            "timestamp": self.timestamp.isoformat(),
            "duration_seconds": self.duration_seconds,
            "motion_level": self.motion_level,
            "region": self.region,
            "detected_by": self.detected_by,
            "recorded_clip": self.recorded_clip
        }


@dataclass
class Alert:
    """Alert generated by the system"""
    id: str
    camera_id: int
    camera_name: str
    severity: AlertSeverity
    message: str
    timestamp: datetime
    acknowledged: bool = False
    resolved: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict:
        return {
            "id": self.id,
            "camera_id": self.camera_id,
            "camera_name": self.camera_name,
            "severity": self.severity.value,
            "message": self.message,
            "timestamp": self.timestamp.isoformat(),
            "acknowledged": self.acknowledged,
            "resolved": self.resolved,
            "metadata": self.metadata
        }


@dataclass
class StaffPresence:
    """Staff presence tracking"""
    staff_name: str
    camera_id: int
    property_name: str
    check_in: datetime
    check_out: Optional[datetime] = None
    zone: str = ""
    
    @property
    def duration_hours(self) -> float:
        if self.check_out:
            return (self.check_out - self.check_in).total_seconds() / 3600
        return (datetime.now() - self.check_in).total_seconds() / 3600


class NotificationHandler:
    """Handles notifications for the camera system"""
    
    def __init__(self):
        self.notification_queue: List[Dict] = []
        self.sms_enabled = True
        self.email_enabled = True
        self.push_enabled = True
        self.webhook_urls: Set[str] = set()
        
    def add_webhook(self, url: str) -> None:
        self.webhook_urls.add(url)
        
    def send(self, alert: Alert) -> None:
        """Send notification based on severity"""
        notification = {
            "type": alert.severity.value,
            "camera": alert.camera_name,
            "message": alert.message,
            "timestamp": alert.timestamp.isoformat()
        }
        self.notification_queue.append(notification)
        logger.info(f"Notification sent: {notification['message']}")
        
        # In production, implement actual notification delivery:
        # - SMS via Twilio
        # - Email via SMTP
        # - Push via Firebase
        # - Webhook delivery
        
        if alert.severity in (AlertSeverity.CRITICAL, AlertSeverity.EMERGENCY):
            self._send_emergency(notification)
            
    def _send_emergency(self, notification: Dict) -> None:
        """Send emergency notifications"""
        logger.warning(f"EMERGENCY NOTIFICATION: {notification['message']}")
        # Implementation for SMS, phone calls, etc.


class CameraAgent:
    """
    Agentic camera monitoring unit.
    Each agent manages a single camera's monitoring and decision-making.
    """
    
    def __init__(self, camera: Camera, notification_handler: NotificationHandler):
        self.camera = camera
        self.notification_handler = notification_handler
        self.running = False
        self.task: Optional[asyncio.Task] = None
        self.detection_history: List[MotionEvent] = []
        self.alert_history: List[Alert] = []
        self.staff_presence: Dict[str, StaffPresence] = {}
        self._motion_cooldown = 30  # seconds between motion alerts
        self._last_motion_alert = None
        self._frame_processor = None
        
    async def start(self) -> None:
        """Start the camera agent"""
        self.running = True
        logger.info(f"Starting camera agent for {self.camera.name} (ID: {self.camera.id})")
        
        while self.running:
            try:
                await self._monitor_loop()
            except Exception as e:
                logger.error(f"Error in camera agent {self.camera.id}: {e}")
                await asyncio.sleep(5)
                
    def stop(self) -> None:
        """Stop the camera agent"""
        self.running = False
        if self.task:
            self.task.cancel()
        logger.info(f"Stopped camera agent for {self.camera.name}")
        
    async def _monitor_loop(self) -> None:
        """Main monitoring loop for the agent"""
        # Simulate frame processing
        await asyncio.sleep(random.uniform(0.5, 2.0))
        
        # Update camera status
        self.camera.uptime_seconds += 2
        self.camera.status = CameraStatus.STREAMING
        
        # Check for motion (simulated)
        if random.random() < 0.15:  # 15% chance of motion
            motion_level = random.randint(3, 9)
            await self._handle_motion_detection(motion_level)
            
        # Check for staff presence changes
        await self._check_staff_presence()
        
        # Health check
        await self._health_check()
        
    async def _handle_motion_detection(self, motion_level: int) -> None:
        """Handle detected motion events"""
        now = datetime.now()
        
        # Prevent alert spam
        if self._last_motion_alert:
            cooldown_remaining = self._motion_cooldown - (now - self._last_motion_alert).total_seconds()
            if cooldown_remaining > 0:
                return
                
        self.camera.motion_status = MotionStatus.MOTION_DETECTED
        self.camera.last_motion_detected = now
        
        # Create motion event
        event = MotionEvent(
            camera_id=self.camera.id,
            camera_name=self.camera.name,
            property_name=self.camera.property_name,
            timestamp=now,
            duration_seconds=random.uniform(2, 15),
            motion_level=motion_level,
            region="main_area"
        )
        self.detection_history.append(event)
        
        # Determine severity based on motion level
        if motion_level >= 8 and self.camera.zone_type in (ZoneType.ENTRY, ZoneType.EXTERIOR):
            severity = AlertSeverity.CRITICAL
            message = f"HIGH motion detected at {self.camera.name} ({self.camera.property_name})"
        elif motion_level >= 6:
            severity = AlertSeverity.WARNING
            message = f"Motion detected at {self.camera.name} ({self.camera.property_name})"
        elif motion_level >= 3:
            severity = AlertSeverity.INFO
            message = f"Low motion activity at {self.camera.name}"
        else:
            severity = AlertSeverity.INFO
            message = f"Minor motion registered at {self.camera.name}"
            
        # Create and send alert
        alert = Alert(
            id=f"alert-{self.camera.id}-{int(now.timestamp())}",
            camera_id=self.camera.id,
            camera_name=self.camera.name,
            severity=severity,
            message=message,
            timestamp=now,
            metadata={"motion_level": motion_level, "duration": event.duration_seconds}
        )
        
        self.alert_history.append(alert)
        
        if severity in (AlertSeverity.CRITICAL, AlertSeverity.EMERGENCY):
            self.notification_handler.send(alert)
            
        self._last_motion_alert = now
        
        # Trigger recording if motion is high
        if motion_level >= 6:
            self.camera.recording = True
            logger.info(f"Recording started on {self.camera.name} due to motion")
            # Simulate recording duration
            asyncio.create_task(self._stop_recording(15))
            
    async def _stop_recording(self, delay_seconds: int) -> None:
        """Stop recording after delay if no new motion"""
        await asyncio.sleep(delay_seconds)
        if self.camera.motion_status == MotionStatus.NO_MOTION:
            self.camera.recording = False
            logger.info(f"Recording stopped on {self.camera.name}")
            
    async def _check_staff_presence(self) -> None:
        """Check for staff presence changes"""
        # Simulated staff presence check
        if random.random() < 0.02 and not self.camera.staff_attending:
            # Staff arrives
            staff_names = ["Faith Wanjiru", "Samuel Mwangi", "Peter Otieno", "Esther Adhiambo"]
            staff = random.choice(staff_names)
            self.camera.staff_attending = staff
            self.staff_presence[staff] = StaffPresence(
                staff_name=staff,
                camera_id=self.camera.id,
                property_name=self.camera.property_name,
                check_in=datetime.now(),
                zone=self.camera.name
            )
            logger.info(f"{staff} checked in at {self.camera.name}")
            
        if random.random() < 0.01 and self.camera.staff_attending:
            # Staff leaves
            staff = self.camera.staff_attending
            if staff in self.staff_presence:
                self.staff_presence[staff].check_out = datetime.now()
                logger.info(f"{staff} checked out from {self.camera.name}")
            self.camera.staff_attending = None
            
    async def _health_check(self) -> None:
        """Perform health check on the camera"""
        if random.random() < 0.001:  # 0.1% chance of camera failure
            self.camera.status = CameraStatus.ERROR
            alert = Alert(
                id=f"health-{self.camera.id}-{int(datetime.now().timestamp())}",
                camera_id=self.camera.id,
                camera_name=self.camera.name,
                severity=AlertSeverity.CRITICAL,
                message=f"Camera {self.camera.name} is offline",
                timestamp=datetime.now(),
                metadata={"error": "connection_timeout"}
            )
            self.alert_history.append(alert)
            self.notification_handler.send(alert)
            
            # Simulate recovery after 30 seconds
            asyncio.create_task(self._recover_camera(30))
            
    async def _recover_camera(self, delay: int) -> None:
        """Recover camera after an error"""
        await asyncio.sleep(delay)
        self.camera.status = CameraStatus.ONLINE
        logger.info(f"Camera {self.camera.name} recovered")
        
    def get_stats(self) -> Dict:
        """Get agent statistics"""
        return {
            "camera_id": self.camera.id,
            "camera_name": self.camera.name,
            "uptime": self.camera.uptime_seconds,
            "motion_events": len(self.detection_history),
            "alerts": len(self.alert_history),
            "current_staff": self.camera.staff_attending,
            "recording": self.camera.recording,
            "status": self.camera.status.value
        }


class CameraMonitoringSystem:
    """
    Main orchestration system for camera monitoring.
    Manages multiple camera agents and provides centralized control.
    """
    
    def __init__(self):
        self.cameras: Dict[int, Camera] = {}
        self.agents: Dict[int, CameraAgent] = {}
        self.notification_handler = NotificationHandler()
        self._running = False
        self._main_task: Optional[asyncio.Task] = None
        self.alert_log: List[Alert] = []
        self.activity_log: List[Dict] = []
        self._active_staff: Set[str] = set()
        
    def add_camera(self, camera: Camera) -> None:
        """Add a camera to the system"""
        self.cameras[camera.id] = camera
        agent = CameraAgent(camera, self.notification_handler)
        self.agents[camera.id] = agent
        logger.info(f"Added camera: {camera.name} ({camera.property_name})")
        
    def remove_camera(self, camera_id: int) -> None:
        """Remove a camera from the system"""
        if camera_id in self.agents:
            self.agents[camera_id].stop()
            del self.agents[camera_id]
            del self.cameras[camera_id]
            logger.info(f"Removed camera ID: {camera_id}")
            
    async def start(self) -> None:
        """Start the entire monitoring system"""
        if self._running:
            return
            
        self._running = True
        logger.info("Starting Camera Monitoring System...")
        
        # Start all camera agents
        for agent in self.agents.values():
            agent.task = asyncio.create_task(agent.start())
            
        # Start main system tasks
        self._main_task = asyncio.create_task(self._system_loop())
        logger.info("Camera Monitoring System started successfully")
        
    async def stop(self) -> None:
        """Stop the entire monitoring system"""
        self._running = False
        logger.info("Stopping Camera Monitoring System...")
        
        # Stop all agents
        for agent in self.agents.values():
            agent.stop()
            
        if self._main_task:
            self._main_task.cancel()
            
        logger.info("Camera Monitoring System stopped")
        
    async def _system_loop(self) -> None:
        """Main system loop for orchestration"""
        while self._running:
            try:
                # Update system health
                await self._system_health_check()
                
                # Process any pending notifications
                await self._process_notifications()
                
                # Log system status periodically
                await self._log_system_status()
                
                await asyncio.sleep(10)
                
            except Exception as e:
                logger.error(f"Error in system loop: {e}")
                await asyncio.sleep(5)
                
    async def _system_health_check(self) -> None:
        """Perform system-wide health check"""
        total_cameras = len(self.cameras)
        online_cameras = sum(1 for c in self.cameras.values() if c.status == CameraStatus.ONLINE)
        
        if online_cameras < total_cameras:
            offline = total_cameras - online_cameras
            logger.warning(f"{offline} camera(s) are offline")
            
    async def _process_notifications(self) -> None:
        """Process queued notifications"""
        if self.notification_handler.notification_queue:
            # Process notifications - in production, send to external services
            pass
            
    async def _log_system_status(self) -> None:
        """Log system status periodically"""
        stats = self.get_system_stats()
        logger.debug(f"System status: {stats['online_cameras']}/{stats['total_cameras']} online")
        
    def get_system_stats(self) -> Dict:
        """Get comprehensive system statistics"""
        total = len(self.cameras)
        online = sum(1 for c in self.cameras.values() if c.status in (CameraStatus.ONLINE, CameraStatus.STREAMING))
        recording = sum(1 for c in self.cameras.values() if c.recording)
        motion = sum(1 for c in self.cameras.values() if c.motion_status == MotionStatus.MOTION_DETECTED)
        staffed = sum(1 for c in self.cameras.values() if c.staff_attending)
        
        return {
            "total_cameras": total,
            "online_cameras": online,
            "recording_cameras": recording,
            "motion_detected": motion,
            "staffed_cameras": staffed,
            "total_alerts": len(self.alert_log),
            "active_staff": list(self._active_staff),
            "system_uptime": time.time() - self._start_time if hasattr(self, '_start_time') else 0
        }
        
    def get_camera_status(self, camera_id: int) -> Optional[Dict]:
        """Get detailed status for a specific camera"""
        if camera_id in self.cameras:
            camera = self.cameras[camera_id]
            agent = self.agents.get(camera_id)
            return {
                "camera": camera.to_dict(),
                "agent_stats": agent.get_stats() if agent else None,
                "recent_motion": [
                    e.to_dict() for e in agent.detection_history[-5:]
                ] if agent else []
            }
        return None
        
    def get_all_cameras(self) -> List[Dict]:
        """Get status for all cameras"""
        return [c.to_dict() for c in self.cameras.values()]
        
    def get_alerts(self, limit: int = 100, severity: Optional[AlertSeverity] = None) -> List[Dict]:
        """Get recent alerts with optional filtering"""
        alerts = self.alert_log
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        return [a.to_dict() for a in alerts[-limit:]]
        
    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert"""
        for alert in self.alert_log:
            if alert.id == alert_id:
                alert.acknowledged = True
                return True
        return False
        
    def resolve_alert(self, alert_id: str) -> bool:
        """Resolve an alert"""
        for alert in self.alert_log:
            if alert.id == alert_id:
                alert.resolved = True
                return True
        return False
        
    def trigger_motion_test(self, camera_id: int) -> bool:
        """Manually trigger a motion test event"""
        if camera_id in self.agents:
            # Create test motion event
            event = MotionEvent(
                camera_id=camera_id,
                camera_name=self.cameras[camera_id].name,
                property_name=self.cameras[camera_id].property_name,
                timestamp=datetime.now(),
                duration_seconds=5.0,
                motion_level=8,
                region="test_zone",
                detected_by="manual-test"
            )
            self.agents[camera_id].detection_history.append(event)
            logger.info(f"Manual motion test triggered on camera {camera_id}")
            return True
        return False
        
    def get_activity_timeline(self, hours: int = 24) -> List[Dict]:
        """Get activity timeline for the past N hours"""
        cutoff = datetime.now() - timedelta(hours=hours)
        return [a for a in self.activity_log if a.get('timestamp', datetime.now()) > cutoff]


def create_default_cameras() -> List[Camera]:
    """Create a default set of cameras for the estate"""
    return [
        Camera(
            id=1,
            name="Nursery",
            property_name="Karen Residence",
            zone_type=ZoneType.NURSERY,
            hue=150,
            brightness=0.55,
            staff_attending="Faith Wanjiru"
        ),
        Camera(
            id=2,
            name="Main Gate",
            property_name="Karen Residence",
            zone_type=ZoneType.ENTRY,
            hue=35,
            brightness=0.4
        ),
        Camera(
            id=3,
            name="Garage",
            property_name="Karen Residence",
            zone_type=ZoneType.GARAGE,
            hue=200,
            brightness=0.35,
            staff_attending="Peter Otieno"
        ),
        Camera(
            id=4,
            name="Kitchen",
            property_name="Runda Residence",
            zone_type=ZoneType.KITCHEN,
            hue=40,
            brightness=0.6,
            staff_attending="Samuel Mwangi"
        ),
        Camera(
            id=5,
            name="Pool & Garden",
            property_name="Runda Residence",
            zone_type=ZoneType.GARDEN,
            hue=170,
            brightness=0.5
        ),
        Camera(
            id=6,
            name="Laundry Room",
            property_name="Runda Residence",
            zone_type=ZoneType.INTERIOR,
            hue=210,
            brightness=0.42,
            staff_attending="Esther Adhiambo"
        ),
        Camera(
            id=7,
            name="Front Porch",
            property_name="Lavington Home",
            zone_type=ZoneType.ENTRY,
            hue=30,
            brightness=0.38
        ),
        Camera(
            id=8,
            name="Kids' Playroom",
            property_name="Lavington Home",
            zone_type=ZoneType.INTERIOR,
            hue=280,
            brightness=0.5,
            staff_attending="Grace Achieng"
        ),
    ]


async def main():
    """Main entry point for the camera monitoring system"""
    system = CameraMonitoringSystem()
    
    # Create and add default cameras
    for camera in create_default_cameras():
        system.add_camera(camera)
    
    # Add a webhook for external integration
    system.notification_handler.add_webhook("https://webhook.mwarokin.estates/monitor")
    
    # Start the system
    await system.start()
    
    # Run for a while and demonstrate functionality
    try:
        print("\n" + "="*60)
        print("Mwarokin Estates - Camera Monitoring System Active")
        print("="*60)
        
        start_time = time.time()
        while time.time() - start_time < 120:  # Run for 2 minutes
            await asyncio.sleep(20)
            
            # Show some stats
            stats = system.get_system_stats()
            print(f"\n[{datetime.now().strftime('%H:%M:%S')}] System Status:")
            print(f"  Cameras: {stats['online_cameras']}/{stats['total_cameras']} online")
            print(f"  Recording: {stats['recording_cameras']} cameras")
            print(f"  Motion detected: {stats['motion_detected']} cameras")
            print(f"  Staffed zones: {stats['staffed_cameras']} cameras")
            
            # Show active cameras
            for camera in system.get_all_cameras():
                if camera['status'] in ('online', 'streaming'):
                    status_emoji = "📹" if camera['recording'] else "✅"
                    staff_info = f"👤 {camera['staff_attending']}" if camera['staff_attending'] else "👤 unattended"
                    print(f"  {status_emoji} {camera['name']} ({camera['property_name']}) - {staff_info}")
                    
    except KeyboardInterrupt:
        print("\nShutting down...")
    finally:
        await system.stop()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nSystem shutdown complete.")
